### ISSUE TITLE
 Blank menu "Manage Reserved Names"

### ISSUE THREAD

**Issue by wvro-org** [getnamingo/registry#63]
Registry -> TLDs -> Managed Reserved Names
<img width="1351" alt="Screenshot 2024-01-02 at 00 32 02" src="https://github.com/getnamingo/registry/assets/66093777/a53c52fa-4e16-42b5-9fb0-2aea765eb351">

**Comment by getpinga** [comment]
Thanks, I can confirm. There should be a logic for adding new reserved names, when the DB is empty. I'll work on it.

**Comment by wvro-org** [comment]
manually added org.example.com ...  to db 

<img width="1324" alt="Screenshot 2024-01-02 at 00 54 40" src="https://github.com/getnamingo/registry/assets/66093777/ed3d2291-6621-42db-beae-fe3c000bb246">
and when the input field is clear(aka del reserved name) it asks to enter domain...

**Comment by getpinga** [comment]
Please replace this file https://github.com/getnamingo/registry/blob/main/cp/app/Controllers/SystemController.php and try again

- Now when empty, will ask to enter at least one domain in each category, there will not be the blank issue.
- If you delete all, it will still ask to enter at least one name. Still working on this.
- About entering the exact domain ,for the moment I can not change that, as it is designed to have reserved names across all TLDs added to the system. That's why there is no TLD.

**Comment by wvro-org** [comment]
Seams to me works fine
<img width="1376" alt="Screenshot 2024-01-02 at 15 25 20" src="https://github.com/getnamingo/registry/assets/66093777/77d6313d-34e0-4dea-b7a2-fdcd35b753af">
---
however check domain only one time displayed "blue" error / Domain "test.test" is not available: domain reserved/restricted (sorry no screen)

or not.... works fine...
---
and now somehow it allowed to delete "reserved" domains and the is only one field with "restricted" domain
and issue with no field for "reserved" domains..... and manually changed in db type from restricted to reserved and now thereis no field for restricted domains...
<img width="1326" alt="Screenshot 2024-01-02 at 15 47 16" src="https://github.com/getnamingo/registry/assets/66093777/4523e907-2298-4f34-9e79-3864f4bac793">
<img width="1338" alt="Screenshot 2024-01-02 at 15 47 48" src="https://github.com/getnamingo/registry/assets/66093777/3157fc27-bfd3-4a05-9bb3-af67069485ea">

**Comment by getpinga** [comment]
This also got fixed. Please test and reopen if still having an issue.
